# New line at the start of the prompt
add_newline = true
# Override prompt order
format = """\

    $username\
    $hostname\
    $env_var\
    $directory\


    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $package\

    $crystal\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $java\
    $julia\
    $nim\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $zig\

    $docker_context\
    $aws\
    $terraform\
    $kubernetes\
    $nix_shell\
    $conda\
    $memory_usage\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $time\
    $character\
"""
# Timeout for starship to check files under the current directory.
# scan_timeout = 10

# Git
[git_branch]
symbol = "ï„¦ "
style = "bold #C50A96"
# truncation_length = 4
# truncation_symbol = ""
disabled = false

[git_commit]
format = "[\\($hash\\)]($style) "
commit_hash_length = 7
disabled = false

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"
disabled = false

[git_status]
format = "$all_status$ahead_behind "
renamed = "Â»"
deleted = "[âœ–](red)"
conflicted = "="
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
untracked = "[â—](red)"
stashed = "ï’"
modified = "[â—](yellow)"
staged = "[â—](green)"
style = "white"
staged_count.enabled = false
staged_count.style = "dimmed green"
disabled = false

# Programming languages
[python]
symbol = "î˜† "
pyenv_version_name = false
pyenv_prefix = "pyenv "
scan_for_pyfiles = true
style = "bold #FED74C"
disabled = false

[php]
symbol = "î˜ˆ "
style = "bold #707FB4"
disabled = true

[haskell]
symbol = "î· "
disabled = true

[golang]
format = "via [î˜§ $version](bold #00ACD7) "
disabled = false

[zig]
symbol = "âš¡ "
style = "bold #F7A41D"
disabled = false

[nim]
symbol = "ïš¤ "
style = "bold #EFC743"
disabled = false

[nodejs]
symbol = "â¬¢ "
style = "bold #77B063"
disabled = false

[purescript]
symbol = "<=> "
style = "bold white"
disabled = false

[elm]
symbol = "î˜¬ "
disabled = false

[ruby]
symbol = "îˆ¾ "
style = "bold #AD1401"
disabled = false

[rust]
symbol = "î¨ "
style = "bold #DEA584"
disabled = false

# System info
[username]
style_root = "bold red"
style_user = "bold #98C379"
show_always = true
disabled = false

[hostname]
ssh_only = true
format = "[$hostname]($style) in "
trim_at = "."
disabled = false

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[jobs]
symbol = "+ "
threshold = 1
style = "white"
disabled = false

# Services
[docker_context]
symbol = "ïŒˆ "
style = "bold #2496ED"
disabled = false

[kubernetes]
symbol = "ï´± "
style = "bold #326DE6"
disabled = false
#[kubernetes.context_aliases]
#"dev.local.cluster.k8s" = "dev"

[aws]
symbol = "îŒ½ "
displayed_items = "all"
style = "bold #F58C0F"
disabled = false

[terraform]
symbol = "ğŸ’  "
show_version = false
style = "bold 105"
disabled = false

[nix_shell]
use_name = true
impure_msg = "impure shell"
pure_msg = "pure shell"
symbol = "ï‹œ "
disabled = false

# Misc
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold green)"
use_symbol_for_status = true

[cmd_duration]
format = "took [$duration]($style) "
min_time = 5000

[time]
use_12hr = true
format = "ï€—[$time]($style) "
time_format = "%I:%M%p"
utc_time_offset = "local"
#time_range = "10:00:00-14:00:00"
disabled = true

[package]
symbol = "ğŸ“¦ "
style = "bold 208"
display_private = false
disabled = true

[line_break]
disabled = false
